[package]
name = "rs"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.x86_64-apple-darwin.dependencies]
libc = "0.2"
glfw = "0.34.0"

[features]
default = []
mikan-bare = []
